import type { Metadata } from "next";
import "./globals.css";
import {Inter,Poppins,Outfit} from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500"],
});

const outfit = Outfit({subsets:["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );  
}
